services:
  uniswap:
    image: gdafund/l3_collectors:latest
    command: uniswap.py
    volumes:
      - type: bind
        source: ./keys
        target: /src/keys
  ethereum:
    image: gdafund/on-chain-data-collection:latest
    command: ethereum.py
    volumes:
      - type: bind
        source: ./keys
        target: /src/keys 
